[plugin]
id = "azure.storage.blob-compiler-plugin"
class = "io.ballerina.lib.azure.storage.blob.plugin.AzureBlobCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/azure.storage.blob-compiler-plugin-@project.version@.jar"
